id: AB639F529
title: White and Red Sur Offerings That Are Very Easy to Apply
type: translation
pechas:
- I1159A159
- I617C8954
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:33:30.454000
  last_modified_at: 2023-01-04 11:33:30.454014
  collections:
  - Chokgyur Dechen Lingpa
  - Works of Tibetan Masters
alignment_to_base:
  I1159A159/9544: '3458'
  I617C8954/1F51: '3458'
